services:
  axis-auto-next:
    container_name: axis-auto-next
    restart: always
    image: node:20.10.0
    ports:
      - 5000:4000
    environment:
      - PORT=4000
    volumes:
      - ./:/usr/src/axis-auto-next
    working_dir: /usr/src/axis-auto-next
    networks:
      - client-network
      
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge